version: '2'
services:
    mall-app:
        image: mall
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://mall-mysql:3306/mall?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=mall-elasticsearch:9300
        ports:
            - 8080:8080
    mall-mysql:
        extends:
            file: mysql.yml
            service: mall-mysql
    mall-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: mall-elasticsearch
