version: '2'
services:
  mall-app:
    image: mall
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:mysql://mall-mysql:3306/mall?useUnicode=true&characterEncoding=utf8&useSSL=false&createDatabaseIfNotExist=true
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
      - SPRING_DATA_JEST_URI=http://mall-elasticsearch:9200
      - SPRING_ELASTICSEARCH_REST_URIS=http://mall-elasticsearch:9200
    ports:
      - 8080:8080
  mall-mysql:
    extends:
      file: mysql.yml
      service: mall-mysql
  mall-elasticsearch:
    extends:
      file: elasticsearch.yml
      service: mall-elasticsearch
